### PR TITLE
Support for installing as a python package

### PR DESCRIPTION
**Pull request by neuromusic**
This pull request adds support for installing the NWB Python API as a full python package.

``` bash
    python install ./setup.py
```

or using pip

``` bash
    pip install ./
```

other changes:
- changed the file naming to be more consistent with python package/module standards (e.g. `from nwb import utils`
- ported documentation to README.md

### CODE REVIEW

**Comment by wvangeit** [comment]
It would be really useful if this PR was merged into the master

**Comment by neuromusic** [comment]
@wvangeit it might be worth looking into the Allen Institute's NWB implementation, which is a bit more fully developed: https://github.com/AllenInstitute/nwb-api/tree/master/ainwb

**Comment by wvangeit** [comment]
@neuromusic Ok, that makes sense, thank you for the link

**Comment by keithg-alleninstitute** [comment]
If you have any questions about the Institute's version of the NWB library, please feel free to contact us, either through github or directly:

  keithg@alleninstitute.org

  roby@alleninstitute.org

Thank you for your interest.

Best wishes,

Keith

**Comment by wvangeit** [comment]
The only question I have at the moment is if anybody is planning to write an NWB reader for the Neo IO library:
https://pythonhosted.org/neo/io.html
I'm starting to write an io layer for the eFEL software:
https://github.com/BlueBrain/eFEL/blob/master/efel/io.py
I was thinking of using Neo IO as backend, but I still need a solution for NWB (and Igor Pro).

**Comment by keithg-alleninstitute** [comment]
I'm unaware of any work on a NEO interface yet. This is certainly a good idea (and important). There is some work going on relating to IGOR but I don't know details.

Best wishes,

Keith

**Comment by neuromusic** [comment]
@wvangeit the question of NEO support for the NWB format is probably best for @apdavison. I don't see any mention of NWB in the NEO repo

**Comment by apdavison** [comment]
NWB support in Neo is definitely on my radar. I've just added a ticket for it: https://github.com/NeuralEnsemble/python-neo/issues/221

**Comment by apdavison** [comment]
@wvangeit there is a ticket in the Neo tracker for Igor Pro, but I don't know if anyone is working on it: https://github.com/NeuralEnsemble/python-neo/issues/109

**Comment by wvangeit** [comment]
Ok, thanks for the update. Might implement something for NWB in eFEL.io in the mean time, but will probably switch to neo.io once the NWB support is implemented.

**Comment by jeffteeters** [comment]
neuromusic - thanks for submitting the pull request.  I'll try to incorporate installing by package into the next update.  I have not done it yet because it requires updating the documentation and the changes I'm making now require other changes to the documentation and I'd rather do them all at once.

**Pull request merged**
